#!/usr/bin/env bash

laptop_dir=~/.config/hypr/laptop-config
desktop_dir=~/.config/hypr/desktop-config

declare -A dest_dirs=(
    ["conf"]="$HOME/.config/hypr/config"
    ["sh"]="$HOME/.config/hypr/scripts"
)

comment="# ATTENTION: This file is automatically generated, manual changes will be overwritten!"

copy_files_from_dir() {
    local src_dir="$1"

    for file in "$src_dir"/*; do
      local filename="$(basename "$file")"

      local ext="${filename##*.}" 
      if [[ -z "${dest_dirs[$ext]}" ]]; then
          echo "Error: Unknown file extension '$ext' for file '$filename'. Skipping." >&2
          continue
      fi

      local dest="${dest_dirs[$ext]}"
      if [[ ! -d "$dest" ]]; then
          echo "Error: Destination directory '$dest' does not exist for file '$filename'. Skipping." >&2
          continue
      fi

      # check if the file has a shebang and insert the comment after it if so
      read -r firstline < "$file"
      if [[ "$firstline" == \#!* ]]; then
          {
              echo "$firstline"
              echo "$comment"
              tail -n +2 "$file"
          } > "$dest/$filename"
      else
          {
              echo "$comment"
              cat "$file"
          } > "$dest/$filename"
      fi
    done
}

case "$(hostname)" in
  nix-laptop)
    echo "Running on Laptop"
    copy_files_from_dir "$laptop_dir"
    ;;

  nix-desktop)
    echo "Running on Desktop"
    copy_files_from_dir "$desktop_dir"
    ;;

  *)
    echo "Unknown system: $(hostname)"
    ;;
esac