#!/usr/bin/env bash

config_dir=~/.config/hypr/config
laptop_dir=~/.config/hypr/laptop-config
desktop_dir=~/.config/hypr/desktop-config

comment="# This file is automatically generated, manual changes will be overwritten!"

case "$(hostname)" in
  nix-laptop)
    echo "Running on Laptop"

    for file in $laptop_dir/*; do
        filename=$(basename "$file")
        echo "Copy file: $filename"

        {
            echo "$comment"
            cat "$laptop_dir/$filename"
        } > "$config_dir/$filename"
    done

    ;;
  nix-desktop)
    echo "Running on Desktop"

    for file in $desktop_dir/*; do
        filename=$(basename "$file")
        echo "Copy file: $filename"

        {
            echo "$comment"
            cat "$desktop_dir/$filename"
        } > "$config_dir/$filename"  
    done

    ;;
  *)
    echo "Unknown system: $(hostname)"
    ;;
esac